# For each branch you want to deploy, create a new workflow file:
# .github/workflows/deploy-dev.yml
name: Deploy Development Site

on:
  push:
    branches: [ web-design ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install, build, and upload site
        uses: withastro/action@v1
        with:
          path: ./dev # Different output path for development
          node-version: 18

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages-development
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
